global:
    scrape_interval: 5s
    evaluation_interval: 5s
scrape_configs:
    - job_name: 'monitoring-app'
      ## Spring boot endpoint for metrics
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      ## App address in Docker container
      static_configs:
      - targets: ['HOST_IP:8080']
